// <auto-generated />
using GameHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameHub.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231206141401_MoreData")]
    partial class MoreData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameHub.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Gotcha! Coming in 2025 only for Ps5",
                            Image = "https://cdn.images.express.co.uk/img/dynamic/143/590x/secondary/GTA-6-trailer-Grand-Theft-Auto-6-gameplay-reveal-5098949.jpg?r=1701793274244",
                            Price = 90.0,
                            Title = "GTA 6"
                        },
                        new
                        {
                            Id = 2,
                            Description = "This game is not a metro simulator",
                            Image = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fstore.steampowered.com%2Fapp%2F412020%2FMetro_Exodus%2F&psig=AOvVaw1p0-qvGm7ScTktVqnAxPUw&ust=1701958359478000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCOjOmo3_-oIDFQAAAAAdAAAAABAE",
                            Price = 30.0,
                            Title = "Metro Exodus"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The goat",
                            Image = "https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Assassin%27s_Creed_Unity_cover.jpg/220px-Assassin%27s_Creed_Unity_cover.jpg",
                            Price = 20.0,
                            Title = "Assassin's Creed Unity"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The second best assassin's creed game",
                            Price = 40.0,
                            Title = "Assassin's Creed Origin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
